### ISSUE TITLE
But where are the examples?

### ISSUE THREAD

**Issue by ReckoningReckoner** [mrseidel/CEMC2016-LargeData#1]
I'm yearning to see the sharknado.

**Comment by mrseidel** [comment]
Sharknado was part of the Arts Night presentation I had proposed, but it was not accepted. This is the one that uses Large Data (http://bit.ly/seidel-bigdata). I haven't finished the presentation yet, nor posted the examples.

Maybe next year Sharknado will arrive!

**Comment by ReckoningReckoner** [comment]
Ah well. The dream lives on. Never forget.
